### ISSUE TITLE
Updated 1.0.5 npm package is broken, src folder is not included

### ISSUE THREAD

**Issue by Abasz** [8beeeaaat/web-ant-plus#9]
I just wanted to mention again that the updated 1.0.5 npm package is broken, as the src folder is not included. So upon install nothing works.

_Originally posted by @Abasz in https://github.com/8beeeaaat/web-ant-plus/issues/8#issuecomment-2098224231_

**Comment by 8beeeaaat** [comment]
Wow!! I'm sorry about this.
Just a moment.

**Comment by 8beeeaaat** [comment]
I have one question, why do you need the src directory?
After `npm install web-ant-plus` is it used in your application as follows?
If you can give me specific details of the error, I might be able to your help.

```
import {
  HeartRateSensor,
  HeartRateSensorState,
...
} from "web-ant-plus";
```

In my environment, web-ant-plus with npm install is working properly.

![スクリーンショット 2024-07-23 9 58 01](https://github.com/user-attachments/assets/f3dd8115-1068-4488-9e9e-0c1503b7e658)

![スクリーンショット 2024-07-23 9 55 03](https://github.com/user-attachments/assets/2ec4318b-3c47-438a-81c6-98d1e59ec326)


In general, NPM packages do not include development sources (src).It is bloated and users need the deliverables provided as a result of the build = dist directory, not the development sources.

**Comment by Abasz** [comment]
Sorry, I can see that the 1.0.6 version includes the dist folder. I did not check that it was updated to 1.0.6 and in my package.json version was tied to that (1.0.5) as a specific version.
